More test updates

diff --git a/doc/examples/gmtest.in b/doc/examples/gmtest.in
--- a/doc/examples/gmtest.in
+++ b/doc/examples/gmtest.in
@@ -2,13 +2,14 @@
 #
 # $Id$
 #
-# Functions to be used with test scripts
+# Bash script inclusion to test all GMT examples.
+# It sets the environment such that the examples are created as in the manual.
 
 # Where the current script resides (need absolute path)
-script_name=$(basename "$1")
+script_name=$1
+script_dir=$(dirname "$1")
 current_dir=$PWD
-cd "$(dirname "$1")"
-src="$PWD"
+shift
 
 # Determine if awk is buggy
 result=`echo 1 | awk '{print sin($1)}'`
@@ -22,30 +23,20 @@ else
   export AWK=awk
 fi
 
-getbox () {
-  # Expects -Joption and distance in km from map center
-  range=$( (echo -$2 -$2; echo $2 $2) | mapproject $1 -R0/360/-90/90 -I -Fk -C)
-  printf " -R%f/%f/%f/%fr\n" $range
-}
-
-getrect () {
-  # Expects xmin xmax ymin ymax in km relative to map center
-  # -R and -J are set by preceding GMT commands
-  (echo -$1 -$1; echo -$1 $1; echo $1 $1; echo $1 -$1) | mapproject -R -J -I -Fk -C
-}
-
 # Temporary change LANG to C
 LANG=C
 
-# Use executables from GMT_BINARY_DIR, fallback to CMAKE_INSTALL_PREFIX/GMT_BINDIR
-export PATH="@GMT_BINARY_DIR_PATH@:@GMT_SOURCE_DIR@/src:@CMAKE_INSTALL_PREFIX@/@GMT_BINDIR@:${PATH}"
-export GMT5_SHAREDIR="@GMT_SOURCE_DIR@/share"
-export GMT_USERDIR="@GMT_BINARY_DIR@/share"
-export GMT_DATADIR="@GMT_SOURCE_DIR@/doc/scripts"
-
 # Define variables that are needed *within* test scripts
+GMT_BINARY_DIR="@GMT_BINARY_DIR@"
 GMT_SOURCE_DIR="@GMT_SOURCE_DIR@"
+EXTRA_FONTS_DIR="@CMAKE_CURRENT_SOURCE_DIR@/ex31/fonts"
 GRAPHICSMAGICK="@GRAPHICSMAGICK@"
+src="$GMT_SOURCE_DIR/doc/examples/$script_dir"
+
+# Use executables from GMT_BINARY_DIR, fallback to CMAKE_INSTALL_PREFIX/GMT_BINDIR
+export PATH="@GMT_BINARY_DIR_PATH@:$GMT_SOURCE_DIR/src:@CMAKE_INSTALL_PREFIX@/@GMT_BINDIR@:${PATH}"
+export GMT_SHAREDIR="$GMT_SOURCE_DIR/share"
+export GMT_USERDIR="$GMT_BINARY_DIR/share"
 
 # Reset error count
 ERROR=0
@@ -55,17 +46,18 @@ function make_pdf()
 {
   pdf="${ps%.ps}.pdf"
   test -f "$ps" || return 1
-  ps2raster -Tf -A -P -Ggs "$ps" || ((++ERROR))
+  ps2raster -Tf -A -P -Ggs -C-sFONTPATH=${EXTRA_FONTS_DIR} "$ps" || ((++ERROR))
   test -f "$pdf" || ((++ERROR))
 }
 
 # Compare the ps file with its original.
 pscmp () {
-  test -f "$ps" || return 1
-  if ! [ -x "$GRAPHICSMAGICK" ]; then
-    echo "[PASS] (without comparison)"
-    return
-  fi
+test -f "$ps" || return 1
+if ! [ -x "$GRAPHICSMAGICK" ]; then
+  echo "[PASS] (without comparison)"
+  return
+fi
+for ps in *.ps ; do
   # syntax: gm compare [ options ... ] reference-image [ options ... ] compare-image [ options ... ]
   rms=$(${GRAPHICSMAGICK} compare -density 200 -maximum-error 0.001 -highlight-color magenta -highlight-style assign -metric rmse -file "${ps%.ps}.png" "$ps" "$src/$ps") || pscmpfailed="yes"
   rms=$(sed -nE '/Total:/s/ +Total: ([0-9.]+) .+/\1/p' <<< "$rms")
@@ -77,13 +69,14 @@ pscmp () {
   if [ "$pscmpfailed" ]; then
     now=$(date "+%F %T")
     echo "${ps%.ps}: RMS Error = $rms [FAIL]"
-    echo "$now ${ps%.ps}: RMS Error = $rms" >> $current_dir/fail_count.d
+    echo "$now ${ps%.ps}: RMS Error = $rms" >> "$current_dir/fail_count.d"
     make_pdf "$ps" # try to make pdf file
     ((++ERROR))
   else
     test -z "$rms" && rms=NA
     echo "${ps%.ps}: RMS Error = $rms [PASS]"
   fi
+done
 }
 
 # Make sure to cleanup at end
@@ -119,18 +112,17 @@ trap on_err ERR SIGSEGV SIGTRAP SIGBUS
 # Create a temporary directory exec_dir in the build dir
 # Then copy all of its contents (except *.ps files)
 # Run remainder of this GMT script there
-exec_dir="$current_dir/${script_name%.sh}"
+exec_dir="$current_dir/$script_dir"
+rm -rf "$exec_dir"
 mkdir -p "$exec_dir"
 cd "$exec_dir"
-shift
+ln -fs "$src"/* .
+rm -f *.ps *.sh
 
 # Start with proper GMT defaults
-gmtset -Du PS_CHAR_ENCODING ISOLatin1+
-
-# Tentative PS file name
-ps="${script_name%.sh}.ps"
+gmtset -Du FORMAT_TIME_LOGO "Version 5"
 
 # Now run the original script
-. "$src/$script_name"
+. "$GMT_SOURCE_DIR/doc/examples/$script_name"
 
 # vim: ft=sh
