More test updates

diff --git a/trunk/test/gmtest.in b/trunk/test/gmtest.in
--- a/trunk/test/gmtest.in
+++ b/trunk/test/gmtest.in
@@ -11,10 +11,7 @@
 script_name=$1
 script_dir=$(dirname "$1")
 current_dir="$PWD"
-
-header () {
-  printf "%-72s\n" "$script_name: $1"
-}
+shift
 
 # Temporary change LANG to C
 LANG=C
@@ -47,13 +44,15 @@ function make_pdf()
 
 # Compare the ps file with its original. Check $ps against original $ps or against $1.ps (if $1 given)
 pscmp () {
-  test -f "$ps" || return 1
-  if ! [ -x "$GRAPHICSMAGICK" ]; then
-    echo "[PASS] (without comparison)"
-    return
-  fi
+test ${#ps} -gt 0 || return 0
+test -f "$ps" || return 1
+if ! [ -x "$GRAPHICSMAGICK" ]; then
+  echo "[PASS] (without comparison)"
+  return
+fi
+for ps in *.ps ; do
   # syntax: gm compare [ options ... ] reference-image [ options ... ] compare-image [ options ... ]
-  rms=$(${GRAPHICSMAGICK} compare -density 200 -maximum-error 0.001 -highlight-color magenta -highlight-style assign -metric rmse -file "${ps%.ps}.png" "$ps" "$src/${1:-$ps}") || pscmpfailed="yes"
+  rms=$(${GRAPHICSMAGICK} compare -density 200 -maximum-error 0.001 -highlight-color magenta -highlight-style assign -metric rmse -file "${ps%.ps}.png" "$ps" "$src/${psref:-$ps}") || pscmpfailed="yes"
   rms=$(sed -nE '/Total:/s/ +Total: ([0-9.]+) .+/\1/p' <<< "$rms")
   if [ -z "$rms" ]; then
     rms="NA"
@@ -70,6 +69,7 @@ pscmp () {
     test -z "$rms" && rms=NA
     echo "${scriptname%.sh}: RMS Error = $rms [PASS]"
   fi
+done
 }
 
 passfail () {
@@ -85,14 +85,22 @@ passfail () {
 }
 
 # Make sure to cleanup at end
-function on_exit()
+function cleanup()
 {
-  set +e
-  trap - EXIT # Restore EXIT trap
   cd "$current_dir" # get out of exec_dir before removing it
   test "$ERROR" -eq 0 && rm -rf "$exec_dir"
   echo "exit status: $ERROR"
   exit $ERROR
+}
+
+# Test the output image(s) and/or fail file before exiting
+function on_exit()
+{
+  set +e
+  trap - EXIT # Restore EXIT trap
+  pscmp
+  passfail
+  cleanup
 }
 trap on_exit EXIT
 
@@ -103,21 +111,19 @@ function on_err()
   set +e
   trap - EXIT ERR SIGSEGV SIGTRAP SIGBUS # Restore trap
   ((++ERROR))
-  on_exit
+  cleanup
 }
 trap on_err ERR SIGSEGV SIGTRAP SIGBUS
 
 # Create a temporary directory exec_dir in the build dir
 # and run remainder of this GMT script there
 exec_dir="$current_dir/${script_name%.sh}"
+rm -rf "$exec_dir"
 mkdir -p "$exec_dir"
 cd "$exec_dir"
 
 # Start with proper GMT defaults
 gmtset -Du
-
-# Tentative PS file name
-ps="${script_name%.sh}.ps"
 
 # Now run the original script
 . "$GMT_SOURCE_DIR/test/$script_name"
