Using new "check" script for scripts (avoids "functions.sh" and "$src")

diff --git a/trunk/doc/examples/check.in b/trunk/doc/examples/check.in
--- a/trunk/doc/examples/check.in
+++ b/trunk/doc/examples/check.in
@@ -5,8 +5,8 @@
 # Bash script inclusion to test all GMT examples.
 # It sets the environment such that the examples are created as in the manual.
 
-scriptname=$(basename "$1")
-currentdir=$PWD
+script_name=$(basename "$1")
+current_dir=$PWD
 
 # Determine if awk is buggy
 result=`echo 1 | awk '{print sin($1)}'`
@@ -48,11 +48,11 @@ function make_pdf()
 # Compare the ps file with its original.
 pscmp () {
 test -f "$ps" || return 1
+if ! [ -x "$GRAPHICSMAGICK" ]; then
+  echo "[PASS] (without comparison)"
+  return
+fi
 for ps in *.ps ; do
-  if ! [ -x "$GRAPHICSMAGICK" ]; then
-    echo "[PASS] (without comparison)"
-    return
-  fi
   # syntax: gm compare [ options ... ] reference-image [ options ... ] compare-image [ options ... ]
   rms=$(${GRAPHICSMAGICK} compare -density 200 -maximum-error 0.001 -highlight-color magenta -highlight-style assign -metric rmse -file "${ps%.ps}.png" "$ps" "$src/$ps") || pscmpfailed="yes"
   rms=$(sed -nE '/Total:/s/ +Total: ([0-9.]+) .+/\1/p' <<< "$rms")
@@ -63,13 +63,13 @@ for ps in *.ps ; do
   fi
   if [ "$pscmpfailed" ]; then
     now=$(date "+%F %T")
-    echo "$ps: RMS Error = $rms [FAIL]"
-    echo "$now $ps: RMS Error = $rms" >> ../fail_count.d
+    echo "${ps%.ps}: RMS Error = $rms [FAIL]"
+    echo "$now ${ps%.ps}: RMS Error = $rms" >> ../fail_count.d
     make_pdf "$ps" # try to make pdf file
     ((++ERROR))
   else
     test -z "$rms" && rms=NA
-    echo "$ps: RMS Error = $rms [PASS]"
+    echo "${ps%.ps}: RMS Error = $rms [PASS]"
   fi
 done
 }
@@ -111,7 +111,7 @@ src="$PWD"
 # Create a temporary directory exec_dir in the build dir
 # Then copy all of its contents (except *.ps files)
 # Run remainder of this GMT script there
-exec_dir="@CMAKE_CURRENT_BINARY_DIR@/${src##*/}"
+exec_dir="$current_dir/${src##*/}"
 mkdir -p "$exec_dir"
 cd "$exec_dir"
 ln -fs "$src"/* .
@@ -121,7 +121,10 @@ shift
 # Start with proper GMT defaults
 gmtset -Du FORMAT_TIME_LOGO "Version 5"
 
+# Tentative PS file name
+ps=${script_name%.sh}.ps
+
 # Now run the original script
-. "$scriptname"
+. "$src/$script_name"
 
 # vim: ft=sh
diff --git a/trunk/doc/scripts/check.in b/trunk/doc/scripts/check.in
--- a/trunk/doc/scripts/check.in
+++ b/trunk/doc/scripts/check.in
@@ -1,9 +1,11 @@
+#!/bin/bash
 #
 # $Id$
 #
 # Functions to be used with test scripts
 
-scriptname=$(basename "$0")
+script_name=$(basename "$1")
+current_dir=$PWD
 
 # Determine if awk is buggy
 result=`echo 1 | awk '{print sin($1)}'`
@@ -19,7 +21,7 @@ fi
 
 getbox () {
   # Expects -Joption and distance in km from map center
-  range=$((echo -$2 -$2; echo $2 $2) | mapproject $1 -R0/360/-90/90 -I -Fk -C)
+  range=$( (echo -$2 -$2; echo $2 $2) | mapproject $1 -R0/360/-90/90 -I -Fk -C)
   printf " -R%f/%f/%f/%fr\n" $range
 }
 
@@ -36,17 +38,17 @@ LANG=C
 export PATH="@GMT_BINARY_DIR_PATH@:@GMT_SOURCE_DIR@/src:@CMAKE_INSTALL_PREFIX@/@GMT_BINDIR@:${PATH}"
 export GMT_SHAREDIR="@GMT_SOURCE_DIR@/share"
 export GMT_USERDIR="@GMT_BINARY_DIR@/share"
+export GMT_DATADIR="@GMT_SOURCE_DIR@/doc/scripts"
 
 # Define variables that are needed *within* test scripts
 GMT_SOURCE_DIR="@GMT_SOURCE_DIR@"
-EXTRA_FONTS_DIR="@CMAKE_CURRENT_SOURCE_DIR@/ex31/fonts"
 GRAPHICSMAGICK="@GRAPHICSMAGICK@"
 
 # Reset error count
 ERROR=0
 
 # Where the current script resides (need absolute path)
-cd "$(dirname "$0")"
+cd "$(dirname "$1")"
 src="${PWD}"
 
 # Convert PS to PDF
@@ -54,11 +56,11 @@ function make_pdf()
 {
   pdf="${ps%.ps}.pdf"
   test -f "$ps" || return 1
-  ps2raster -Tf -A -P -Ggs -C-sFONTPATH=${EXTRA_FONTS_DIR} "$ps" || ((++ERROR))
+  ps2raster -Tf -A -P -Ggs "$ps" || ((++ERROR))
   test -f "$pdf" || ((++ERROR))
 }
 
-# Compare the ps file with its original. Check $ps against original $ps or against $1.ps (if $1 given)
+# Compare the ps file with its original.
 pscmp () {
   test -f "$ps" || return 1
   if ! [ -x "$GRAPHICSMAGICK" ]; then
@@ -66,7 +68,7 @@ pscmp () {
     return
   fi
   # syntax: gm compare [ options ... ] reference-image [ options ... ] compare-image [ options ... ]
-  rms=$(${GRAPHICSMAGICK} compare -density 200 -maximum-error 0.001 -highlight-color magenta -highlight-style assign -metric rmse -file "${ps%.ps}.png" "$ps" "$src/${1:-$ps}") || pscmpfailed="yes"
+  rms=$(${GRAPHICSMAGICK} compare -density 200 -maximum-error 0.001 -highlight-color magenta -highlight-style assign -metric rmse -file "${ps%.ps}.png" "$ps" "$src/$ps") || pscmpfailed="yes"
   rms=$(sed -nE '/Total:/s/ +Total: ([0-9.]+) .+/\1/p' <<< "$rms")
   if [ -z "$rms" ]; then
     rms="NA"
@@ -75,20 +77,20 @@ pscmp () {
   fi
   if [ "$pscmpfailed" ]; then
     now=$(date "+%F %T")
-    echo "RMS Error = $rms [FAIL]"
-    echo "$now ${src##*/}/${ps%.ps}: RMS Error = $rms" >> ../fail_count.d
+    echo "${ps%.ps}: RMS Error = $rms [FAIL]"
+    echo "$now ${ps%.ps}: RMS Error = $rms" >> ../fail_count.d
     make_pdf "$ps" # try to make pdf file
     ((++ERROR))
   else
     test -z "$rms" && rms=NA
-    echo "RMS Error = $rms [PASS]"
+    echo "${ps%.ps}: RMS Error = $rms [PASS]"
   fi
 }
 
 # Make sure to cleanup at end
 function cleanup()
 {
-  cd "@GMT_BINARY_DIR@" # get out of exec_dir before removing it
+  cd "$current_dir" # get out of exec_dir before removing it
   test "${ERROR}" -eq 0 && rm -rf "${exec_dir}"
   echo "exit status: ${ERROR}"
   exit ${ERROR}
@@ -116,15 +118,20 @@ function on_err()
 trap on_err ERR SIGSEGV SIGTRAP SIGBUS
 
 # Create a temporary directory exec_dir in the build dir
-# and run remainder of this GMT script there
-exec_dir="@CMAKE_CURRENT_BINARY_DIR@/${scriptname%.sh}"
-mkdir -p "${exec_dir}"
-cd "${exec_dir}"
+# Then copy all of its contents (except *.ps files)
+# Run remainder of this GMT script there
+exec_dir="$current_dir/${script_name%.sh}"
+mkdir -p "$exec_dir"
+cd "$exec_dir"
+shift
 
 # Start with proper GMT defaults
 gmtset -Du PS_CHAR_ENCODING ISOLatin1+
 
-# Convert script name to PS filename
-ps="${scriptname%.sh}.ps"
+# Tentative PS file name
+ps=${script_name%.sh}.ps
+
+# Now run the original script
+. "$src/$script_name"
 
 # vim: ft=sh
